#!/bin/bash
## begin license ##
#
# "Kennisnet Json-LD" provides tools for handling tools
#
# Copyright (C) 2024 Seecr (Seek You Too B.V.) https://seecr.nl
# Copyright (C) 2024 Stichting Kennisnet https://www.kennisnet.nl
#
# This file is part of "Kennisnet Json-LD"
#
# "Kennisnet Json-LD" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# "Kennisnet Json-LD" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with "Kennisnet Json-LD"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
## end license ##

this_dir=$(pwd)
env_dir=${this_dir}/env

PYTHON_EXC=python3
PROJECT_NAME=edurep

if [ -d "${env_dir}" ]; then
    echo "Environment already exists: ${env_dir}"
else
    echo "Creating virtualenv: ${env_dir}"
    ${PYTHON_EXC} -m venv --prompt ${PROJECT_NAME} ${env_dir} --system-site-package
    cat > ${env_dir}/pip.conf <<EOF
[global]
index-url = https://devpi.vpn.seecr.nl/seecr/dev/+simple/
EOF
    source ${env_dir}/bin/activate
    ${PYTHON_EXC} -m pip install --upgrade pip
    ${PYTHON_EXC} -m pip install --editable ${this_dir}
fi
